spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discocovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://mscredito-eureka:8761/eureka

